version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_IMAGE_TAG}
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - ${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}
    networks:
      - mia_rete

  kafka0:
    image: confluentinc/cp-kafka:${KAFKA_IMAGE_TAG}
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_BROKER_ONE_PORT}:${KAFKA_BROKER_ONE_PORT}
      - ${KAFKA_BROKER_ONE_EXTERNAL_PORT}:${KAFKA_BROKER_ONE_EXTERNAL_PORT}
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:${ZOOKEEPER_CLIENT_PORT}'
      ZOOKEEPER_SASL_ENABLED: 'false'
      KAFKA_ADVERTISED_LISTENERS: ${SECURITY_PROTOCOL}://kafka0:${KAFKA_BROKER_ONE_PORT},${SECURITY_PROTOCOL}_EXTERNAL://${PUBLIC_IP}:${KAFKA_BROKER_ONE_EXTERNAL_PORT}

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_EXTERNAL:SASL_PLAINTEXT
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: ${SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: ${KAFKA_SASL_MECHANISMS}
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/configs/kafka_server_jaas.conf"
    volumes:
      - ./configs:/etc/kafka/configs
    networks:
      - mia_rete

  kafka1:
    image: confluentinc/cp-kafka:${KAFKA_IMAGE_TAG}
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_BROKER_TWO_PORT}:${KAFKA_BROKER_TWO_PORT}
      - ${KAFKA_BROKER_TWO_EXTERNAL_PORT}:${KAFKA_BROKER_TWO_EXTERNAL_PORT}
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:${ZOOKEEPER_CLIENT_PORT}'
      ZOOKEEPER_SASL_ENABLED: 'false'
      KAFKA_ADVERTISED_LISTENERS: ${SECURITY_PROTOCOL}://kafka1:${KAFKA_BROKER_TWO_PORT},${SECURITY_PROTOCOL}_EXTERNAL://${PUBLIC_IP}:${KAFKA_BROKER_TWO_EXTERNAL_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_EXTERNAL:SASL_PLAINTEXT
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: ${SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: ${KAFKA_SASL_MECHANISMS}
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/configs/kafka_server_jaas.conf"
    volumes:
      - ./configs:/etc/kafka/configs
    networks:
      - mia_rete 

  kafka2:
    image: confluentinc/cp-kafka:${KAFKA_IMAGE_TAG}
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_BROKER_THREE_PORT}:${KAFKA_BROKER_THREE_PORT}
      - ${KAFKA_BROKER_THREE_EXTERNAL_PORT}:${KAFKA_BROKER_THREE_EXTERNAL_PORT}
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:${ZOOKEEPER_CLIENT_PORT}'
      ZOOKEEPER_SASL_ENABLED: 'false'
      KAFKA_ADVERTISED_LISTENERS: ${SECURITY_PROTOCOL}://kafka2:${KAFKA_BROKER_THREE_PORT},${SECURITY_PROTOCOL}_EXTERNAL://${PUBLIC_IP}:${KAFKA_BROKER_THREE_EXTERNAL_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_EXTERNAL:SASL_PLAINTEXT
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: ${SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: ${KAFKA_SASL_MECHANISMS}
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/configs/kafka_server_jaas.conf"
    volumes:
      - ./configs:/etc/kafka/configs
    networks:
      - mia_rete

networks:
  mia_rete:
    driver: bridge
